version: "3.8"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: localservicereview
      MYSQL_USER: reviewservice
      MYSQL_PASSWORD: reviewservice
      MYSQL_ROOT_PASSWORD: reviewservice
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 30

  review_service_api:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SLEEP_LENGTH=10
    
    
